[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pixi_exec_utils"
readme.workspace = true
repository.workspace = true
version = "0.1.0"

[profile.release]
# Enable Link Time Optimization.
lto = true
# Reduce number of codegen units to increase optimizations.
codegen-units = 1
# Optimize for size.
opt-level = "z"
# Abort on panic.
panic = "abort"
# Automatically strip symbols from the binary.
debug = false
strip = true

[dependencies]
tracing = "0.1"

[dev-dependencies]
rstest = { workspace = true }
